// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcP05STkyps7mDiyQtNVzjOJYHFbhDPw',
    appId: '1:406837924425:web:fb4e40ce2069a18768e598',
    messagingSenderId: '406837924425',
    projectId: 'farmdairy-61a48',
    authDomain: 'farmdairy-61a48.firebaseapp.com',
    storageBucket: 'farmdairy-61a48.appspot.com',
    measurementId: 'G-DW4XN18FGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsK3OisS9FIhyKsOeX9JBjFpBYTEgfHTc',
    appId: '1:406837924425:android:450d971aba7f63f568e598',
    messagingSenderId: '406837924425',
    projectId: 'farmdairy-61a48',
    storageBucket: 'farmdairy-61a48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOAm9ait3ZqJsluS29hO3fUnYWUiBaWc',
    appId: '1:406837924425:ios:c34f94529297da6068e598',
    messagingSenderId: '406837924425',
    projectId: 'farmdairy-61a48',
    storageBucket: 'farmdairy-61a48.appspot.com',
    iosBundleId: 'com.example.farmDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeOAm9ait3ZqJsluS29hO3fUnYWUiBaWc',
    appId: '1:406837924425:ios:c34f94529297da6068e598',
    messagingSenderId: '406837924425',
    projectId: 'farmdairy-61a48',
    storageBucket: 'farmdairy-61a48.appspot.com',
    iosBundleId: 'com.example.farmDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcP05STkyps7mDiyQtNVzjOJYHFbhDPw',
    appId: '1:406837924425:web:4bf9668e0bf17bca68e598',
    messagingSenderId: '406837924425',
    projectId: 'farmdairy-61a48',
    authDomain: 'farmdairy-61a48.firebaseapp.com',
    storageBucket: 'farmdairy-61a48.appspot.com',
    measurementId: 'G-QWKXJHX089',
  );
}
